# -*- coding: utf-8 -*-
"""homework_python10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/elekarpovi/801223bf8b2045981d811325e0ffe79b/homework_python10.ipynb

| Задание 44 |
| --- |
| В ячейке ниже представлен код генерирующий DataFrame, которая состоит всего из 1 столбца. Ваша задача перевести его в one hot вид. Сможете ли вы это сделать без get_dummies?

import random
lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI'lst})
data.head() |
"""

import pandas as pd
import random
lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI':lst})
data.head()

data.loc[data['whoAmI'] == 'human', 'whoAmI_human'] = '1'
data.loc[data['whoAmI'] == 'robot', 'whoAmI_robot'] = '1'
data.loc[data['whoAmI'] == 'robot', 'whoAmI_human'] = '0'
data.loc[data['whoAmI'] == 'human', 'whoAmI_robot'] = '0'
data.head()

del data['whoAmI']
data